import {
  LayoutGrid,
  ShieldCheck,
  FileText,
  AlertCircle,
  UserCircle,
  Award,
  Link as LinkIcon,
  SquareMousePointer,
  CreditCard,
  Cookie,
  SquareDashedBottom,
  ChevronsRight,
  Table,
  FileInput,
  Type,
  LogIn,
  UserPlus,
  Loader,
  AlertTriangle,
  Newspaper,
  Mail,
  HelpCircle,
  Sparkles,
  Image as ImageIcon,
  Briefcase,
  Tags,
  Users,
  MessageSquare,
  LayoutDashboard,
  PanelBottom,
  Grid2x2
} from 'lucide-react';

export const components = [
  {
    category: 'UI Elements',
    category_slug: 'ui-elements',
    icon: LayoutGrid,
    items: [
      {
        name: 'Alerts',
        link: '/components/ui-elements/alerts',
        description:
          'Inform users about important actions, system messages, or feedback with styled alert components.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/alerts/Basic.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Basic with Icon',
            path: '/components/ui-elements/alerts/Basic with Icon.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Basic with Button',
            path: '/components/ui-elements/alerts/Basic with Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Basic with Icon and Button',
            path: '/components/ui-elements/alerts/Basic with Icon and Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat',
            path: '/components/ui-elements/alerts/Flat.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat with Icon',
            path: '/components/ui-elements/alerts/Flat with Icon.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat with Button',
            path: '/components/ui-elements/alerts/Flat with Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat with Icon and Button',
            path: '/components/ui-elements/alerts/Flat with Icon and Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat Border',
            path: '/components/ui-elements/alerts/Flat Border.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat Border with Icon',
            path: '/components/ui-elements/alerts/Flat Border with Icon.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat Border with Button',
            path: '/components/ui-elements/alerts/Flat Border with Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Flat Border with Icon and Button',
            path: '/components/ui-elements/alerts/Flat Border with Icon and Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
        ],
        icon: AlertCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Avatars',
        link: '/components/ui-elements/avatars',
        description:
          'Display user profile images or placeholders in a compact and customizable format.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/avatars/Basic.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Border',
            path: '/components/ui-elements/avatars/Basic with Border.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Border and Indicator',
            path: '/components/ui-elements/avatars/Basic with Border and Indicator.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic with Text',
            path: '/components/ui-elements/avatars/Basic with Text.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: UserCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Badges',
        link: '/components/ui-elements/badges',
        description:
          'Highlight statuses, labels, or notifications with small, colorful indicators.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/Basic.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Icon',
            path: '/components/ui-elements/badges/Basic with Icon.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Close Button',
            path: '/components/ui-elements/badges/Basic with Close Button.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Themed',
            path: '/components/ui-elements/badges/Basic Themed.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat',
            path: '/components/ui-elements/badges/Flat.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Icon',
            path: '/components/ui-elements/badges/Flat with Icon.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Close Button',
            path: '/components/ui-elements/badges/Flat with Close Button.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Themed',
            path: '/components/ui-elements/badges/Flat Themed.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: Award,
        tag: false,
        updated: false,
      },
      {
        name: 'Breadcrumbs',
        link: '/components/ui-elements/breadcrumbs',
        description:
          'Show the users navigation path and improve site structure visibility with breadcrumb trails.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/breadcrumbs/1.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Full',
            path: '/components/ui-elements/breadcrumbs/2.html',
            fullPage: true,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Full Container',
            path: '/components/ui-elements/breadcrumbs/3.html',
            fullPage: true,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Full Center',
            path: '/components/ui-elements/breadcrumbs/4.html',
            fullPage: true,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: LinkIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Buttons',
        link: '/components/ui-elements/buttons',
        description:
          'Trigger actions with versatile, accessible, and customizable button components.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/buttons/Basic.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Group',
            path: '/components/ui-elements/buttons/Basic Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Compact',
            path: '/components/ui-elements/buttons/Basic Compact.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Compact Group',
            path: '/components/ui-elements/buttons/Basic Compact Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Inverted',
            path: '/components/ui-elements/buttons/Basic Inverted.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Inverted Group',
            path: '/components/ui-elements/buttons/Basic Inverted Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Inverted Compact',
            path: '/components/ui-elements/buttons/Basic Inverted Compact.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Inverted Compact Group',
            path: '/components/ui-elements/buttons/Basic Inverted Compact Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Outlined',
            path: '/components/ui-elements/buttons/Outlined.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Outlined Group',
            path: '/components/ui-elements/buttons/Outlined Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Outlined Compact',
            path: '/components/ui-elements/buttons/Outlined Compact.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Outlined Compact Group',
            path: '/components/ui-elements/buttons/Outlined Compact Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat',
            path: '/components/ui-elements/buttons/Flat.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat Group',
            path: '/components/ui-elements/buttons/Flat Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat Compact',
            path: '/components/ui-elements/buttons/Flat Compact.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat Compact Group',
            path: '/components/ui-elements/buttons/Flat Compact Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat Inverted',
            path: '/components/ui-elements/buttons/Flat Inverted.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat Inverted Group',
            path: '/components/ui-elements/buttons/Flat Inverted Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat Inverted Compact',
            path: '/components/ui-elements/buttons/Flat Inverted Compact.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat Inverted Compact Group',
            path: '/components/ui-elements/buttons/Flat Inverted Compact Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: SquareMousePointer,
        tag: false,
        updated: false,
      },
      {
        name: 'Cards',
        link: '/components/ui-elements/cards',
        description:
          'Organize content into flexible containers, perfect for previews, profiles, or product info.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/1.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Card with image',
            path: '/components/ui-elements/cards/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Card with footer',
            path: '/components/ui-elements/cards/3.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Card with button',
            path: '/components/ui-elements/cards/4.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Card with image and button',
            path: '/components/ui-elements/cards/5.html',
            fullWidth: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Card with badge',
            path: '/components/ui-elements/cards/6.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Stats card 1',
            path: '/components/ui-elements/cards/7.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Stats card 2',
            path: '/components/ui-elements/cards/8.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
        ],
        icon: CreditCard,
        tag: false,
        updated: false,
      },
      {
        name: 'Cookies',
        link: '/components/ui-elements/cookies',
        description:
          'Notify users about cookie usage and consent with sleek, dismissible banners.',
        data: [
          {
            name: 'With emoji',
            path: '/components/ui-elements/cookies/1.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'With icon',
            path: '/components/ui-elements/cookies/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: Cookie,
        tag: false,
        updated: false,
      },
      {
        name: 'Images',
        link: '/components/ui-elements/images',
        description:
          'Display images responsively with optional styling for aspect ratio, borders, and shadows.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/images/1.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Image with hover',
            path: '/components/ui-elements/images/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Image with Text on hover',
            path: '/components/ui-elements/images/3.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Image with complex hover',
            path: '/components/ui-elements/images/4.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: ImageIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Modals',
        link: '/components/ui-elements/modals',
        description:
          'Create layered dialogs for confirmations, forms, or extra content without navigating away.',
        data: [
          {
            name: 'Basic with button',
            path: '/components/ui-elements/modals/1.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic with button',
            path: '/components/ui-elements/modals/2.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic with button',
            path: '/components/ui-elements/modals/3.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic with button',
            path: '/components/ui-elements/modals/4.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
        ],
        icon: SquareDashedBottom,
        tag: false,
        updated: false,
      },
      {
        name: 'Paginations',
        link: '/components/ui-elements/pagination',
        description:
          'Divide content into manageable sections with navigable pagination controls.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/pagination/1.html',
            fullPage: false,
            height: 100,
            requiresJS: true,
          },
        ],
        icon: ChevronsRight,
        tag: false,
        updated: false,
      },
      {
        name: 'Tables',
        link: '/components/ui-elements/tables',
        description:
          'Present structured data with clean, styled, and responsive table layouts.',
        data: [
          {
            name: 'Spaced',
            path: '/components/ui-elements/tables/1.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Compact',
            path: '/components/ui-elements/tables/2.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Invoice',
            path: '/components/ui-elements/tables/3.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Invoice 2',
            path: '/components/ui-elements/tables/4.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Table,
        tag: false,
        updated: false,
      },
    ],
  },
  {
    category: 'Forms',
    category_slug: 'forms',
    icon: ShieldCheck,
    items: [
      {
        name: 'Forms',
        link: '/components/forms/forms',
        description:
          'Combine inputs, buttons, and layout components to build full-featured, accessible forms.',
        data: [
          {
            name: 'Contact Us',
            path: '/components/forms/forms/1.html',
            fullPage: false,
            height: 700,
            requiresJS: false,
          },
        ],
        icon: FileInput,
        tag: false,
        updated: false,
      },
      {
        name: 'Inputs',
        link: '/components/forms/inputs',
        description:
          'Collect user data with styled text fields, checkboxes, radios, and more.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/inputs/1.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Input with button',
            path: '/components/forms/inputs/2.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Disabled',
            path: '/components/forms/inputs/3.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
        ],
        icon: Type,
        tag: false,
        updated: false,
      },
      {
        name: 'Sign in',
        link: '/components/forms/sign-in',
        description:
          'Provide users with a secure, clean interface to log into their account.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/sign-in/1.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: LogIn,
        tag: false,
        updated: false,
      },
      {
        name: 'Register',
        link: '/components/forms/register',
        description:
          'Allow users to create new accounts with a simple and user-friendly registration form.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/register/1.html',
            fullPage: false,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: UserPlus,
        tag: false,
        updated: false,
      },
      {
        name: 'Skeleton',
        link: '/components/forms/skeleton',
        description:
          'Display animated placeholders while loading content to improve perceived performance.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/skeleton/1.html',
            fullPage: true,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Loader,
        tag: false,
        updated: false,
      },
    ],
  },
  {
    category: 'Pages',
    category_slug: 'pages',
    icon: FileText,
    items: [
      {
        name: '404 Pages',
        link: '/components/pages/404-pages',
        description:
          'Guide users back on track with visually engaging “Page Not Found” templates.',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/404-pages/1.html',
            fullPage: true,
            height: 800,
            requiresJS: false,
          },
        ],
        icon: AlertTriangle,
        tag: false,
        updated: false,
      },
      {
        name: 'Blog',
        link: '/components/pages/blog',
        description:
          'Show blog posts with clean layouts optimized for readability and engagement.',
        data: [
          {
            name: 'Basic with heading, image and text',
            path: '/components/pages/blog/1.html',
            fullPage: true,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: Newspaper,
        tag: false,
        updated: false,
      },
      {
        name: 'Contact',
        link: '/components/pages/contact',
        description:
          'Let users reach out with form-based or informational contact page designs.',
        data: [
          {
            name: 'Simple with text and form',
            path: '/components/pages/contact/1.html',
            fullPage: true,
            height: 700,
            requiresJS: false,
          },
        ],
        icon: Mail,
        tag: false,
        updated: false,
      },
      {
        name: 'FAQ',
        link: '/components/pages/faq',
        description:
          'Answer common questions clearly with toggle-based or list-based FAQ sections.',
        data: [
          {
            name: 'Simple with expand',
            path: '/components/pages/faq/1.html',
            fullPage: true,
            height: 400,
            requiresJS: true,
          },
        ],
        icon: HelpCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Features',
        link: '/components/pages/features',
        description:
          'Highlight product or service features with structured and attractive layouts.',
        data: [
          {
            name: 'Simple with heading and feature blocks',
            path: '/components/pages/features/1.html',
            fullPage: true,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Sparkles,
        tag: false,
        updated: false,
      },
      {
        name: 'Heros',
        link: '/components/pages/heros',
        description:
          'Create attention-grabbing headers for landing pages with call-to-action and imagery.',
        data: [
          {
            name: 'Simple with image, text and buttons',
            path: '/components/pages/heros/1.html',
            fullPage: true,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Simple with image, text and buttons 2',
            path: '/components/pages/heros/2.html',
            fullPage: true,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: ImageIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Portfolio',
        link: '/components/pages/portfolio',
        description:
          'Showcase projects, case studies, or work samples with elegant layouts.',
        data: [
          {
            name: 'Simple with heading and hover effect',
            path: '/components/pages/portfolio/1.html',
            fullPage: true,
            height: 800,
            requiresJS: false,
          },
        ],
        icon: Briefcase,
        tag: false,
        updated: false,
      },
      {
        name: 'Pricing',
        link: '/components/pages/pricing',
        description:
          'Compare plans or offers using visually balanced pricing tables and cards.',
        data: [
          {
            name: 'Simple with heading',
            path: '/components/pages/pricing/1.html',
            fullPage: true,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: Tags,
        tag: false,
        updated: false,
      },
      {
        name: 'Teams',
        link: '/components/pages/teams',
        description:
          'Introduce team members with styled profiles, roles, and social links.',
        data: [
          {
            name: 'Simple with heading and blocks',
            path: '/components/pages/teams/1.html',
            fullPage: true,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: Users,
        tag: false,
        updated: false,
      },
      {
        name: 'Testimonials',
        link: '/components/pages/testimonials',
        description:
          'Build trust with customer or client feedback in carousel or grid formats.',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/testimonials/1.html',
            fullPage: true,
            height: 700,
            requiresJS: false,
          },
        ],
        icon: MessageSquare,
        tag: false,
        updated: false,
      },
    ],
  },
  {
    category: 'Layouts',
    category_slug: 'layouts',
    icon: LayoutDashboard,
    items: [
      {
        name: 'Layouts',
        link: '/components/layouts/layouts',
        description:
          'Combine inputs, buttons, and layout components to build full-featured, accessible forms.',
        data: [
          {
            name: 'Basic',
            path: '/components/layouts/layouts/Basic.html',
            fullPage: true,
            height: 500,
            requiresJS: true,
          },
        ],
        icon: Grid2x2,
        tag: true,
        updated: false,
      },
      {
        name: 'Footers',
        link: '/components/layouts/footers',
        description:
          'Add site-wide footers with navigation, contact info, and legal links.',
        data: [
          {
            name: 'Footers',
            path: '/components/layouts/footers/Basic.html',
            fullPage: true,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: PanelBottom,
        tag: false,
        updated: false,
      },
    ],
  },
];