import {
  LayoutGrid,
  ShieldCheck,
  FileText,
  AlertCircle,
  UserCircle,
  Award,
  Link as LinkIcon,
  SquareMousePointer,
  CreditCard,
  Cookie,
  SquareDashedBottom,
  Layout,
  ChevronsRight,
  PanelLeft,
  Table,
  FileInput,
  Type,
  LogIn,
  UserPlus,
  Loader,
  AlertTriangle,
  Newspaper,
  Mail,
  HelpCircle,
  Sparkles,
  LayoutTemplate,
  Image as ImageIcon,
  Briefcase,
  Tags,
  Users,
  MessageSquare,
} from 'lucide-react';

export const components = [
  {
    category: 'UI Elements',
    category_slug: 'ui-elements',
    icon: LayoutGrid,
    items: [
      {
        name: 'Alerts',
        link: '/components/ui-elements/alerts',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/alerts/1.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/alerts/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: AlertCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Avatars',
        link: '/components/ui-elements/avatars',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/avatars/1.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/avatars/2.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/avatars/3.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/avatars/4.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: UserCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Badges',
        link: '/components/ui-elements/badges',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/1.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/2.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/3.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/4.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/5.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/6.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: Award,
        tag: false,
        updated: false,
      },
      {
        name: 'Breadcrumbs',
        link: '/components/ui-elements/breadcrumbs',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/breadcrumbs/1.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: LinkIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Buttons',
        link: '/components/ui-elements/buttons',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/buttons/2.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/buttons/3.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: SquareMousePointer,
        tag: false,
        updated: false,
      },
      {
        name: 'Cards',
        link: '/components/ui-elements/cards',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/1.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/3.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/4.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/5.html',
            fullWidth: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Basic with badge and button',
            path: '/components/ui-elements/cards/6.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/7.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/8.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
        ],
        icon: CreditCard,
        tag: false,
        updated: false,
      },
      {
        name: 'Cookies',
        link: '/components/ui-elements/cookies',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/cookies/1.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/cookies/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: Cookie,
        tag: false,
        updated: false,
      },
      {
        name: 'Images',
        link: '/components/ui-elements/images',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/images/1.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/images/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/images/3.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/images/4.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: ImageIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Modals',
        link: '/components/ui-elements/modals',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/modals/1.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
        ],
        icon: SquareDashedBottom,
        tag: false,
        updated: false,
      },
      {
        name: 'Navbars',
        link: '/components/ui-elements/navbars',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/navbars/1.html',
            fullPage: true,
            height: 400,
            requiresJS: true,
          },
        ],
        icon: Layout,
        tag: false,
        updated: false,
      },
      {
        name: 'Paginations',
        link: '/components/ui-elements/pagination',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/pagination/1.html',
            fullPage: false,
            height: 200,
            requiresJS: true,
          },
        ],
        icon: ChevronsRight,
        tag: false,
        updated: false,
      },
      {
        name: 'Sidebars',
        link: '/components/ui-elements/sidebars',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/sidebars/1.html',
            fullPage: true,
            height: 600,
            requiresJS: true,
          },
        ],
        icon: PanelLeft,
        tag: false,
        updated: false,
      },
      {
        name: 'Tables',
        link: '/components/ui-elements/tables',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/tables/1.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/tables/2.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/ui-elements/tables/3.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Table,
        tag: false,
        updated: false,
      },
    ],
  },
  {
    category: 'Forms',
    category_slug: 'forms',
    icon: ShieldCheck,
    items: [
      {
        name: 'Forms',
        link: '/components/forms/forms',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/forms/1.html',
            fullPage: false,
            height: 700,
            requiresJS: false,
          },
        ],
        icon: FileInput,
        tag: false,
        updated: false,
      },
      {
        name: 'Inputs',
        link: '/components/forms/inputs',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/inputs/1.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/forms/inputs/2.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/forms/inputs/3.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
        ],
        icon: Type,
        tag: false,
        updated: false,
      },
      {
        name: 'Sign in',
        link: '/components/forms/sign-in',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/sign-in/1.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: LogIn,
        tag: false,
        updated: false,
      },
      {
        name: 'Register',
        link: '/components/forms/register',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/register/1.html',
            fullPage: false,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: UserPlus,
        tag: false,
        updated: false,
      },
      {
        name: 'Skeleton',
        link: '/components/forms/skeleton',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/skeleton/1.html',
            fullPage: true,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Loader,
        tag: false,
        updated: false,
      },
    ],
  },
  {
    category: 'Pages',
    category_slug: 'pages',
    icon: FileText,
    items: [
      {
        name: '404 Pages',
        link: '/components/pages/404-pages',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/404-pages/1.html',
            fullPage: true,
            height: 800,
            requiresJS: false,
          },
        ],
        icon: AlertTriangle,
        tag: false,
        updated: false,
      },
      {
        name: 'Blog',
        link: '/components/pages/blog',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/blog/1.html',
            fullPage: true,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: Newspaper,
        tag: false,
        updated: false,
      },
      {
        name: 'Contact',
        link: '/components/pages/contact',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/contact/1.html',
            fullPage: true,
            height: 700,
            requiresJS: false,
          },
        ],
        icon: Mail,
        tag: false,
        updated: false,
      },
      {
        name: 'FAQ',
        link: '/components/pages/faq',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/faq/1.html',
            fullPage: true,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: HelpCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Features',
        link: '/components/pages/features',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/features/1.html',
            fullPage: true,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Sparkles,
        tag: false,
        updated: false,
      },
      {
        name: 'Footers',
        link: '/components/pages/footers',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/footers/1.html',
            fullPage: true,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: LayoutTemplate,
        tag: false,
        updated: false,
      },
      {
        name: 'Heros',
        link: '/components/pages/heros',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/heros/1.html',
            fullPage: true,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Basic',
            path: '/components/pages/heros/2.html',
            fullPage: true,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: ImageIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Portfolio',
        link: '/components/pages/portfolio',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/portfolio/1.html',
            fullPage: true,
            height: 800,
            requiresJS: false,
          },
        ],
        icon: Briefcase,
        tag: false,
        updated: false,
      },
      {
        name: 'Pricing',
        link: '/components/pages/pricing',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/pricing/1.html',
            fullPage: true,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: Tags,
        tag: false,
        updated: false,
      },
      {
        name: 'Teams',
        link: '/components/pages/teams',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/teams/1.html',
            fullPage: true,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: Users,
        tag: false,
        updated: false,
      },
      {
        name: 'Testimonials',
        link: '/components/pages/testimonials',
        description: 'Description',
        data: [
          {
            name: 'Basic',
            path: '/components/pages/testimonials/1.html',
            fullPage: true,
            height: 700,
            requiresJS: false,
          },
        ],
        icon: MessageSquare,
        tag: false,
        updated: false,
      },
    ],
  },
];
