import {
  LayoutGrid,
  ShieldCheck,
  FileText,
  AlertCircle,
  UserCircle,
  Award,
  Link as LinkIcon,
  SquareMousePointer,
  CreditCard,
  Cookie,
  SquareDashedBottom,
  ChevronsRight,
  Table,
  FileInput,
  Type,
  LogIn,
  UserPlus,
  Loader,
  AlertTriangle,
  Newspaper,
  Mail,
  HelpCircle,
  Sparkles,
  Image as ImageIcon,
  Briefcase,
  Tags,
  Users,
  MessageSquare,
  LayoutDashboard,
  PanelBottom,
  Grid2x2,
} from 'lucide-react';

export const components = [
  {
    category: 'UI Elements',
    category_slug: 'ui-elements',
    icon: LayoutGrid,
    items: [
      {
        name: 'Alerts',
        link: '/components/ui-elements/alerts',
        description: 'Inform users about important actions, system messages, or feedback with styled alert components.',
        data: [
          {
            name: 'Alert',
            path: '/components/ui-elements/alerts/Basic.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Alert with Icon',
            path: '/components/ui-elements/alerts/Basic with Icon.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Alert with Button',
            path: '/components/ui-elements/alerts/Basic with Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Alert with Button and Border',
            path: '/components/ui-elements/alerts/Flat with Button.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Alert with Border',
            path: '/components/ui-elements/alerts/Flat Border.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
        ],
        icon: AlertCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Avatars',
        link: '/components/ui-elements/avatars',
        description: 'Display user profile images or placeholders in a compact and customizable format.',
        data: [
          {
            name: 'Basic with Border',
            path: '/components/ui-elements/avatars/Basic with Border.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Border and Indicator',
            path: '/components/ui-elements/avatars/Basic with Border and Indicator.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
        ],
        icon: UserCircle,
        tag: false,
        updated: false,
      },
      {
        name: 'Badges',
        link: '/components/ui-elements/badges',
        description: 'Highlight statuses, labels, or notifications with small, colorful indicators.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/badges/Basic.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Icon',
            path: '/components/ui-elements/badges/Basic with Icon.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic with Close Button',
            path: '/components/ui-elements/badges/Basic with Close Button.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Flat',
            path: '/components/ui-elements/badges/Flat.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: Award,
        tag: false,
        updated: false,
      },
      {
        name: 'Breadcrumbs',
        link: '/components/ui-elements/breadcrumbs',
        description: 'Show the users navigation path and improve site structure visibility with breadcrumb trails.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/breadcrumbs/1.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Full',
            path: '/components/ui-elements/breadcrumbs/2.html',
            fullPage: true,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Full Container',
            path: '/components/ui-elements/breadcrumbs/3.html',
            fullPage: true,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Full Center',
            path: '/components/ui-elements/breadcrumbs/4.html',
            fullPage: true,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: LinkIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Buttons',
        link: '/components/ui-elements/buttons',
        description: 'Trigger actions with versatile, accessible, and customizable button components.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/buttons/Basic.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Basic Group',
            path: '/components/ui-elements/buttons/Basic Group.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
          {
            name: 'Outlined',
            path: '/components/ui-elements/buttons/Outlined.html',
            fullPage: false,
            height: 100,
            requiresJS: false,
          },
        ],
        icon: SquareMousePointer,
        tag: false,
        updated: false,
      },
      {
        name: 'Cards',
        link: '/components/ui-elements/cards',
        description: 'Organize content into flexible containers, perfect for previews, profiles, or product info.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/cards/1.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
          {
            name: 'Card with image',
            path: '/components/ui-elements/cards/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Card with footer',
            path: '/components/ui-elements/cards/3.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Card with button',
            path: '/components/ui-elements/cards/4.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Card with image and button',
            path: '/components/ui-elements/cards/5.html',
            fullWidth: false,
            height: 500,
            requiresJS: false,
          },
          {
            name: 'Card with badge',
            path: '/components/ui-elements/cards/6.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
          {
            name: 'Stats card 1',
            path: '/components/ui-elements/cards/7.html',
            fullPage: false,
            height: 300,
            requiresJS: false,
          },
        ],
        icon: CreditCard,
        tag: false,
        updated: false,
      },
      {
        name: 'Cookies',
        link: '/components/ui-elements/cookies',
        description: 'Notify users about cookie usage and consent with sleek, dismissible banners.',
        data: [
          {
            name: 'With emoji',
            path: '/components/ui-elements/cookies/1.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'With icon',
            path: '/components/ui-elements/cookies/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: Cookie,
        tag: false,
        updated: false,
      },
      {
        name: 'Images',
        link: '/components/ui-elements/images',
        description: 'Display images responsively with optional styling for aspect ratio, borders, and shadows.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/images/1.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Image with hover',
            path: '/components/ui-elements/images/2.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Image with Text on hover',
            path: '/components/ui-elements/images/3.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
          {
            name: 'Image with complex hover',
            path: '/components/ui-elements/images/4.html',
            fullPage: false,
            height: 400,
            requiresJS: false,
          },
        ],
        icon: ImageIcon,
        tag: false,
        updated: false,
      },
      {
        name: 'Paginations',
        link: '/components/ui-elements/pagination',
        description: 'Divide content into manageable sections with navigable pagination controls.',
        data: [
          {
            name: 'Basic',
            path: '/components/ui-elements/pagination/1.html',
            fullPage: false,
            height: 100,
            requiresJS: true,
          },
        ],
        icon: ChevronsRight,
        tag: false,
        updated: false,
      },
      {
        name: 'Tables',
        link: '/components/ui-elements/tables',
        description: 'Present structured data with clean, styled, and responsive table layouts.',
        data: [
          {
            name: 'Spaced',
            path: '/components/ui-elements/tables/1.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Table,
        tag: false,
        updated: false,
      },
    ],
  },
  {
    category: 'Forms',
    category_slug: 'forms',
    icon: ShieldCheck,
    items: [
      {
        name: 'Forms',
        link: '/components/forms/forms',
        description: 'Combine inputs, buttons, and layout components to build full-featured, accessible forms.',
        data: [
          {
            name: 'Contact Us',
            path: '/components/forms/forms/1.html',
            fullPage: false,
            height: 700,
            requiresJS: false,
          },
        ],
        icon: FileInput,
        tag: false,
        updated: false,
      },
      {
        name: 'Inputs',
        link: '/components/forms/inputs',
        description: 'Collect user data with styled text fields, checkboxes, radios, and more.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/inputs/1.html',
            fullPage: false,
            height: 200,
            requiresJS: false,
          },
        ],
        icon: Type,
        tag: false,
        updated: false,
      },
      {
        name: 'Sign in',
        link: '/components/forms/sign-in',
        description: 'Provide users with a secure, clean interface to log into their account.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/sign-in/1.html',
            fullPage: false,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: LogIn,
        tag: false,
        updated: false,
      },
      {
        name: 'Register',
        link: '/components/forms/register',
        description: 'Allow users to create new accounts with a simple and user-friendly registration form.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/register/1.html',
            fullPage: false,
            height: 600,
            requiresJS: false,
          },
        ],
        icon: UserPlus,
        tag: false,
        updated: false,
      },
      {
        name: 'Skeleton',
        link: '/components/forms/skeleton',
        description: 'Display animated placeholders while loading content to improve perceived performance.',
        data: [
          {
            name: 'Basic',
            path: '/components/forms/skeleton/1.html',
            fullPage: true,
            height: 500,
            requiresJS: false,
          },
        ],
        icon: Loader,
        tag: false,
        updated: false,
      },
    ],
  },
];
